### ISSUE TITLE
Need to modify for recently change of relic-toolkit

### ISSUE THREAD

**Issue by tell** [emp-toolkit/emp-pvc#1]
relic-toolkit is massively modified https://github.com/relic-toolkit/relic/commit/5518ed1a8c9039ac29c72b4f1b170eae9936f57c , so that emp-tool, emp-ot, and emp-pvc should follow it.
See https://github.com/tell/emp-env and its Travis CI results for details.

**Comment by wangxiao1254** [comment]
code updated. However, there is a new naming confliction to be resolved. If you are using MacOS, you will need to resolve it locally for now. See https://github.com/relic-toolkit/relic/issues/106

**Comment by wangxiao1254** [comment]
Should be resolved by now. Please close it after verification on your local setup.

**Comment by tell** [comment]
Thanks! I confirmed on my repository, close this issue.
