### ISSUE TITLE
Make install and TLS reference error

### ISSUE THREAD

**Issue by nitincic** [emp-toolkit/emp-pvc#3]
Make install doesn't seem to work. Apparently "install" hasn't been defined in the makefile.
Also, I get the following error while I perform make.

[ 75%] Linking CXX executable ../bin/test_pvc.cpp_exe
/usr/bin/ld: _ZN3emp16CircuitExecution9circ_execE: TLS reference in CMakeFiles/test_pvc.cpp_exe.dir/test_pvc.cpp.o mismatches non-TLS definition in /usr/local/lib/libemp-tool.so section .bss
/usr/local/lib/libemp-tool.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_pvc.cpp_exe.dir/build.make:106: recipe for target 'bin/test_pvc.cpp_exe' failed
make[2]: *** [bin/test_pvc.cpp_exe] Error 1
CMakeFiles/Makefile2:140: recipe for target 'test/CMakeFiles/test_pvc.cpp_exe.dir/all' failed
make[1]: *** [test/CMakeFiles/test_pvc.cpp_exe.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangxiao1254** [comment]
install: Yes. Install is not defined. We define install when the code is a useful building block in other protocols.
Please recompile emp-tool with "-DTHREADING=on" and reinstall it.
See https://github.com/emp-toolkit/emp-pvc/blob/master/.travis.yml#L33

**Comment by nitincic** [comment]
Great, thanks. This worked.
It might be useful to update the step 5 in the installation instructions to "cd emp-pvc && cmake . && sudo make" here (https://github.com/emp-toolkit/emp-pvc).
